# Generated by Django 5.2.4 on 2025-08-06 01:05

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.manager.CustomUserManager()),
            ],
        ),
    ]
