# Generated by Django 6.0 on 2025-12-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
