# Generated by Django 6.0 on 2025-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_verification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
